### ISSUE TITLE
Hella IBS Current Resolution

### ISSUE THREAD

**Issue by pwm802** [mestrode/IBS-Sensor-Library#2]
Does anyone know the resolution of the IBS current register value?

**Comment by mestrode** [comment]
Ibat = (float((long(LinBus->LinMessage[2]) << 16) + (long(LinBus->LinMessage[1]) << 8) + long(LinBus->LinMessage[0]) - 2000000L)) / 1000.0;

Theoretical 1mA resolution
and a range of +- 2000.000 Amps in the register

**Comment by pwm802** [comment]
Thank you
